name: agora_rtc_engine
description: Flutter plugin for Agora Video SDK.
version: 1.0.10
author: Agora.io
homepage: https://www.agora.io

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^3.0.0

flutter:
  plugin:
    androidPackage: io.agora.agorartcengine
    pluginClass: AgoraRtcEnginePlugin
